Include more unittests (#14)
* Remove html file
* Add test to check if the input data is properly tokenized
* Adjust logger
* Remove unused variable token_gene_dict
* Include geneformer unittests for tokenization

* IDK why but this single test made an scggpt test
fail. No idea why as they are in different modules
and should not be related.
The failure is:
FAILED tests/test_scgpt/test_sampler.py::test_subsets_batch_sampler - assert [[0, 1, 2], [3, 4], [5, 6, 7], [8, 9]] != [[0, 1, 2], [3, 4], [5, 6, 7], [8, 9]]

* Add coverage report
* Include downloads otherwise does not work
* Cache pip dependencies
* Add branch coverage
* Upload coverage report as artifact
* Apparently pytest--cov needs an __init__ file